export const products = [
  {
    id: 1,
    title: "Leather Jacket",
    category: "gown",
    price: 249.99,
    img: "/public/jacket.jpg",
  },
  {
    id: 2,
    title: "Arrow Shirt",
    category: "shirt",
    price: 15.99,
    img: "/public/shirt.jpg",
  },
  {
    id: 3,
    title: "Black Jumper",
    category: "shirt",
    price: 14.99,
    img: "/public/jumper.jpg",
  },
  {
    id: 4,
    title: "Brown Shoes",
    category: "shoes",
    price: 149.99,
    img: "/public/shoes.jpg",
  },
  {
    id: 5,
    title: "Black Coat",
    category: "coat",
    price: 69.99,
    img: "/public/levi_peacoat_black.jpg",
  },
  {
    id: 6,
    title: "Blue Jeans",
    category: "jeans",
    price: 39.99,
    img: "/public/jeans.jpg",
  },
  {
    id: 7,
    title: "Grey Jumper",
    category: "shirt",
    price: 24.99,
    img: "/public/sweater.jpg",
  },
  {
    id: 8,
    title: "Bomber Jacket",
    category: "jacket",
    price: 49.99,
    img: "/public/flatseven_bomber_jacket_black.jpg",
  },
  {
    id: 9,
    title: "Black Raincoat",
    category: "jacket",
    price: 59.99,
    img: "/public/alpha_industried_field_coat_black.jpg",
  },
  {
    id: 10,
    title: "Grey Jacket",
    category: "jacket",
    price: 25.99,
    img: "/public/theory_fuel_jacket.jpg",
  },
  {
    id: 11,
    title: "Square Shirt ",
    category: "shirt",
    price: 35.99,
    img: "/public/rothco_plaid_flannel_shirt_blue_plaid.jpg",
  },
  {
    id: 12,
    title: "Grey T_Shirt",
    category: "shirt",
    price: 14.99,
    img: "/public/oliver_queen_grey_vneck_tshirt.jpg",
  },
];
