export const products = [
  {
    id: 1,
    title: "Leather Jacket",
    category: "gown",
    price: 249.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/oliver_queen_brown_moto_jacket.jpg",
  },
  {
    id: 2,
    title: "Arrow Shirt",
    category: "shirt",
    price: 15.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/carhartt_work_shirt_gravel.jpg",
  },
  {
    id: 3,
    title: "Black Jumper",
    category: "shirt",
    price: 14.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/doublju_henley_navy.jpg",
  },
  {
    id: 4,
    title: "Brown Shoes",
    category: "shoes",
    price: 149.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2016/04/clarks_desert_beeswax_boots.jpg",
  },
  {
    id: 5,
    title: "Black Coat",
    category: "coat",
    price: 69.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/levi_peacoat_black.jpg",
  },
  {
    id: 6,
    title: "Blue Jeans",
    category: "jeans",
    price: 39.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/levis_511_big_springs.jpg",
  },
  {
    id: 7,
    title: "Grey Jumper",
    category: "shirt",
    price: 24.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/oliver_queen_jeans.jpg",
  },
  {
    id: 8,
    title: "Bomber Jacket",
    category: "jacket",
    price: 49.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/flatseven_bomber_jacket_black.jpg",
  },
  {
    id: 9,
    title: "Black Raincoat",
    category: "jacket",
    price: 59.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/alpha_industried_field_coat_black.jpg",
  },
  {
    id: 10,
    title: "Grey Jacket",
    category: "jacket",
    price: 25.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2015/08/theory_fuel_jacket.jpg",
  },
  {
    id: 11,
    title: "Square Shirt ",
    category: "shirt",
    price: 35.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2017/04/rothco_plaid_flannel_shirt_blue_plaid.jpg",
  },
  {
    id: 12,
    title: "Grey T-Shirt",
    category: "shirt",
    price: 14.99,
    img: "https://www.tvstyleguide.com/wp-content/uploads/2017/04/levis_denim_shirt_dark_rinse.jpg",
  },
];
